package FEAPP;


/**
* FEAPP/FEOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Ling/Desktop/eclipse-workspace/FE_DRRS_Group/src/FE.idl
* Tuesday, November 28, 2017 5:21:42 PM EST
*/

public interface FEOperations 
{
  boolean Login (String id);
  boolean[] createRoom (String id, String room_Number, String date, String[] Time_Slots);
  boolean[] deleteRoom (String id, String room_Number, String date, String[] Time_Slots);
  String bookRoom (String id, String campusName, String room_Number, String date, String Time_Slots);
  String getAvailableTimeSlot (String id, String date);
  boolean cancelBooking (String id, String bookingID);
  String changeReservation (String id, String bookingID, String campusName, String room_Number, String Time_Slots);
} // interface FEOperations
